# Generated by Django 5.2 on 2025-04-20 17:06

import HOME.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_type',
            field=models.CharField(choices=[('nailart', 'Nail Art'), ('makeup', 'Make Up'), ('productreview', 'Product Review')], default='nailart', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(upload_to=HOME.models.upload_path),
        ),
    ]
