# Generated by Django 5.2 on 2025-04-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0002_posts_post_type_alter_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='platform',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('youtube', 'YouTube')], max_length=20, null=True),
        ),
    ]
