# Generated by Django 5.2 on 2025-04-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0003_posts_link_posts_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
