# Generated by Django 5.2 on 2025-04-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0005_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='background_gradient',
            field=models.CharField(default='linear-gradient(to right, white, #86fde8)', max_length=100),
        ),
    ]
