# Generated by Django 5.2 on 2025-04-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0007_alter_sitesettings_background_gradient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='background_gradient',
            field=models.CharField(default='linear-gradient(90deg,rgba(42, 123, 155, 1) 0%, rgba(87, 199, 133, 1) 50%, rgba(237, 221, 83, 1) 100%)', max_length=100),
        ),
    ]
