# Generated by Django 5.2 on 2025-04-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0008_alter_sitesettings_background_gradient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='background_gradient',
            field=models.CharField(default='linear-gradient(90deg,rgba(42, 123, 155, 1) 0%, rgba(87, 199, 133, 1) 50%, rgba(237, 221, 83, 1) 100%)', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='font_family',
            field=models.CharField(default='Arial, sans-serif', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='heading_color',
            field=models.CharField(default='#333', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='text_color',
            field=models.CharField(default='#555', max_length=100),
        ),
    ]
