# Generated by Django 5.2 on 2025-06-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0010_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='cards/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('link', models.URLField()),
            ],
        ),
    ]
