# Generated by Django 5.2 on 2025-06-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0011_homecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecard',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
